apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/customer1/
patches:
  - target:
      kind: SecretProviderClass
      name: customer1-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "9aef45a6-f92b-430c-bc7c-0991d3b61920"
      - op: replace
        path: /spec/parameters/tenantId
        value: "72f7f9cb-1481-43a5-81bf-330c9853b791"
