apiVersion: v1
kind: Service
metadata:
  name: n8n
spec:
  ports:
    - port: 3008
  selector:
    app: n8n
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: n8n-postgres
  type: ClusterIP
