apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: n8n-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "8802ed9c-a9fc-409b-884f-baf5968b7a96"
    keyvaultName: "kv-n8n-mercury"
    tenantId: "72f7f9cb-1481-43a5-81bf-330c9853b791"
    objects: |
      array:
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
  secretObjects:
    - secretName: n8n-container-env
      type: Opaque
      data:
        - objectName: db-user
          key: DB_POSTGRESDB_USER
        - objectName: db-password
          key: DB_POSTGRESDB_PASSWORD
