apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: n8n-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    # aks_keyvault_secrets_provider_client_id from terraform output
    userAssignedIdentityID: "eb46e57f-b9e9-4d8f-ac8b-6df7c196738c"
    keyvaultName: "kv-n8n-mercury"
    # `az account list` -> homeTenantId
    tenantId: "72f7f9cb-1481-43a5-81bf-330c9853b791"
    # these secrets below are the objects already in KeyVault
    objects: |
      array:
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
  # this is part where kubernetes secrets are created with values pulled from above
  secretObjects:
    - secretName: n8n-container-env
      type: Opaque
      data:
        - objectName: db-user
          key: DB_POSTGRESDB_USER
        - objectName: db-password
          key: DB_POSTGRESDB_PASSWORD
